"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.FlowLogsSchema = exports.FlowLogs = exports.AwaitingResponse = exports.BusinessGroupSchema = exports.BusinessGroup = exports.ChatMessage = exports.ContactSchema = exports.Contact = exports.CouponSchema = exports.Coupon = exports.FlowEvent = exports.FunnelSalesSchema = exports.FunnelSales = exports.GroupSchema = exports.Group = exports.IntegrationSchema = exports.Integration = exports.IntegrationLogsSchema = exports.IntegrationLogs = exports.LiveChat = exports.Logs = exports.MacroSchema = exports.Macro = exports.MessageScheduleSchema = exports.MessageSchedule = exports.Notification = exports.Plan = exports.QuestionnaireSchema = exports.Questionnaire = exports.QuestionSchema = exports.AnswerSchema = exports.Transmission = exports.TransmissionControlSchema = exports.TransmissionControl = exports.User = exports.Workspace = exports.mongoose = void 0;
var mongoose_1 = require("mongoose");
Object.defineProperty(exports, "mongoose", { enumerable: true, get: function () { return __importDefault(mongoose_1).default; } });
var workspace_1 = require("./models/workspace");
Object.defineProperty(exports, "Workspace", { enumerable: true, get: function () { return workspace_1.Workspace; } });
var user_1 = require("./models/user");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return user_1.User; } });
var transmissionControl_1 = require("./models/transmissionControl");
Object.defineProperty(exports, "TransmissionControl", { enumerable: true, get: function () { return transmissionControl_1.TransmissionControl; } });
Object.defineProperty(exports, "TransmissionControlSchema", { enumerable: true, get: function () { return transmissionControl_1.TransmissionControlSchema; } });
var transmission_1 = require("./models/transmission");
Object.defineProperty(exports, "Transmission", { enumerable: true, get: function () { return transmission_1.Transmission; } });
var questionnaire_1 = require("./models/questionnaire");
Object.defineProperty(exports, "AnswerSchema", { enumerable: true, get: function () { return questionnaire_1.AnswerSchema; } });
Object.defineProperty(exports, "QuestionSchema", { enumerable: true, get: function () { return questionnaire_1.QuestionSchema; } });
Object.defineProperty(exports, "Questionnaire", { enumerable: true, get: function () { return questionnaire_1.Questionnaire; } });
Object.defineProperty(exports, "QuestionnaireSchema", { enumerable: true, get: function () { return questionnaire_1.QuestionnaireSchema; } });
var plan_1 = require("./models/plan");
Object.defineProperty(exports, "Plan", { enumerable: true, get: function () { return plan_1.Plan; } });
var notification_1 = require("./models/notification");
Object.defineProperty(exports, "Notification", { enumerable: true, get: function () { return notification_1.Notification; } });
var messageSchedule_1 = require("./models/messageSchedule");
Object.defineProperty(exports, "MessageSchedule", { enumerable: true, get: function () { return messageSchedule_1.MessageSchedule; } });
Object.defineProperty(exports, "MessageScheduleSchema", { enumerable: true, get: function () { return messageSchedule_1.MessageScheduleSchema; } });
var macro_1 = require("./models/macro");
Object.defineProperty(exports, "Macro", { enumerable: true, get: function () { return macro_1.Macro; } });
Object.defineProperty(exports, "MacroSchema", { enumerable: true, get: function () { return macro_1.MacroSchema; } });
var logs_1 = require("./models/logs");
Object.defineProperty(exports, "Logs", { enumerable: true, get: function () { return logs_1.Logs; } });
var livechat_1 = require("./models/livechat");
Object.defineProperty(exports, "LiveChat", { enumerable: true, get: function () { return livechat_1.LiveChat; } });
var integrationLogs_1 = require("./models/integrationLogs");
Object.defineProperty(exports, "IntegrationLogs", { enumerable: true, get: function () { return integrationLogs_1.IntegrationLogs; } });
Object.defineProperty(exports, "IntegrationLogsSchema", { enumerable: true, get: function () { return integrationLogs_1.IntegrationLogsSchema; } });
var integration_1 = require("./models/integration");
Object.defineProperty(exports, "Integration", { enumerable: true, get: function () { return integration_1.Integration; } });
Object.defineProperty(exports, "IntegrationSchema", { enumerable: true, get: function () { return integration_1.IntegrationSchema; } });
var group_1 = require("./models/group");
Object.defineProperty(exports, "Group", { enumerable: true, get: function () { return group_1.Group; } });
Object.defineProperty(exports, "GroupSchema", { enumerable: true, get: function () { return group_1.GroupSchema; } });
var funnelSales_1 = require("./models/funnelSales");
Object.defineProperty(exports, "FunnelSales", { enumerable: true, get: function () { return funnelSales_1.FunnelSales; } });
Object.defineProperty(exports, "FunnelSalesSchema", { enumerable: true, get: function () { return funnelSales_1.FunnelSalesSchema; } });
var FlowEvent_1 = require("./models/FlowEvent");
Object.defineProperty(exports, "FlowEvent", { enumerable: true, get: function () { return FlowEvent_1.FlowEvent; } });
var coupon_1 = require("./models/coupon");
Object.defineProperty(exports, "Coupon", { enumerable: true, get: function () { return coupon_1.Coupon; } });
Object.defineProperty(exports, "CouponSchema", { enumerable: true, get: function () { return coupon_1.CouponSchema; } });
var contact_1 = require("./models/contact");
Object.defineProperty(exports, "Contact", { enumerable: true, get: function () { return contact_1.Contact; } });
Object.defineProperty(exports, "ContactSchema", { enumerable: true, get: function () { return contact_1.ContactSchema; } });
var chatmessage_1 = require("./models/chatmessage");
Object.defineProperty(exports, "ChatMessage", { enumerable: true, get: function () { return chatmessage_1.ChatMessage; } });
var businessGroup_1 = require("./models/businessGroup");
Object.defineProperty(exports, "BusinessGroup", { enumerable: true, get: function () { return businessGroup_1.BusinessGroup; } });
Object.defineProperty(exports, "BusinessGroupSchema", { enumerable: true, get: function () { return businessGroup_1.BusinessGroupSchema; } });
var AwaitingResponse_1 = require("./models/AwaitingResponse");
Object.defineProperty(exports, "AwaitingResponse", { enumerable: true, get: function () { return AwaitingResponse_1.AwaitingResponse; } });
var flowLogs_1 = require("./models/flowLogs");
Object.defineProperty(exports, "FlowLogs", { enumerable: true, get: function () { return flowLogs_1.FlowLogs; } });
Object.defineProperty(exports, "FlowLogsSchema", { enumerable: true, get: function () { return flowLogs_1.FlowLogsSchema; } });
